

 
const data=
[
    {
        "id": 1,
        "Name": 'Sumsung TV',
        "price": '26',
        "image": 'image/p1.webp',
        "cat": 'tv',
        "type": 'new',
    },
    {
        "id":2,
        "Name":'Zebronics',
        "price":"34",
        "image":"image/p14.png",
        "cat":'tv',
        "type":'new'
    },
    {
        "id": 3,
        "Name": 'Sumsung TV',
        "price": '26',
        "image": 'image/p15.webp',
        "cat": 'tv',
        "type": 'new',
    },
    {
        "id": 3,
        "Name": 'Sumsung TV',
        "price": '26',
        "image": 'image/p13.jpeg',
        "cat": 'tv',
        "type": 'new',
    },
    {
        "id": 4,
        "Name": 'UV TV',
        "price": '26',
        "image": 'https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcRd8LXwjUdW8iDMc6YlSugpw7AE3ouJDi2JrmQ9QnjfywgQRsVv_oLYdtSVu3naJKLmpD75S4R2dAEW14QTbm3tknc0axWGE7x9ikB0sG3JnVsfDYCAAuJ8OA',
        "cat": 'tv',
        "type": 'new',
    },
    {
        "id": 5,
        "Name": 'Dell',
        "price": '96',
        "image": 'https://www.shutterstock.com/image-photo/poznan-pol-sep-23-2020-600nw-1919355743.jpg',
        "cat": 'laptop',
        "type": 'new',
    },
    {
        "id":6,
        "Name": 'Intex',
        "price": '96',
        "image": 'https://5.imimg.com/data5/IJ/NO/ZR/SELLER-3066699/ned-dell-xps-13-laptop.jpg',
        "cat": 'laptop',
        "type": 'new',
    },
    {
        "id": 7,
        "Name": 'Lenovo',
        "price": '96',
        "image": 'https://www.shutterstock.com/image-photo/jakartaindonesia-wednesday-14-august-2019-260nw-1791315848.jpg',
        "cat": 'laptop',
        "type": 'new',
    },
    {
        "id": 8,
        "Name": 'HP',
        "price": '96',
        "image": 'https://www.shutterstock.com/image-photo/bangkok-thailand-hp-launch-new-260nw-2126914553.jpg',
        "cat": 'laptop',
        "type": 'new',
    },
    {
        "id": 9,
        "Name": 'Headphone',
        "price": '96',
        "image": 'https://m.media-amazon.com/images/W/MEDIAX_792452-T2/images/I/41vBX2nbI6L._SX300_SY300_QL70_FMwebp_.jpg',
        "cat": 'headphone',
        "type": 'new',
    },

    {
        "id": 10,
        "Name": 'Headphone',
        "price": '236',
        "image": 'image/p3.webp',
        "cat": 'headphone',
        "type": 'new',
    },
    {
        "id": 11,
        "Name": 'Headphone',
        "price": '636',
        "image": 'image/p9.jpg',
        "cat": 'headphone',
        "type": 'new',
    },
    {
        "id": 12,
        "Name": 'Headphone',
        "price": '98',
        "image": 'image/p4.webp',
        "cat": 'headphone',
        "type": 'featured',
    },
    {
        "id": 13,
        "Name": 'Smart Watch',
        "price": '59',
        "image": 'image/p5.webp',
        "cat": 'electronics',
        "type": 'featured',
    },
    {
        "id": 14,
        "Name": 'Smart Watch',
        "price": '956',
        "image": 'image/p10.jpg',
        "cat": 'electronics',
        "type": 'featured',
    },
    {
        "id": 15,
        "Name": 'Smart Watch',
        "price": '389',
        "image": 'image/p11.jpg',
        "cat": 'electronics',
        "type": 'featured',
    },
    {
        "id": 16,
        "Name": 'Smart Watch',
        "price": '67',
        "image": 'image/p6.webp',
        "cat": 'electronics',
        "type": 'top',
    },
    {
        "id": 17,
        "Name": 'Speaker',
        "price": '76',
        "image": 'image/p7.webp',
        "cat": 'electronics',
        "type": 'top',
    },
    {
        "id": 18,
        "Name": 'Speaker',
        "price": '87',
        "image": 'image/p8.webp',
        "cat": 'electronics',
        "type": 'top',
    },
    {
        "id": 19,
        "Name": 'product12',
        "price": '807',
        "image": 'image/p12.jpg',
        "cat": 'electronics',
        "type": 'top',
    }
]



module.exports={data};