

 
const data=
[
    {
        "id": 1,
        "Name": 'Sumsung TV',
        "price": '26',
        "image": 'image/p1.webp',
        "cat": 'tv',
        "type": 'new',
    },
    {
        "id":2,
        "Name":'Zebronics',
        "price":"34",
        "image":"image/p14.png",
        "cat":'tv',
        "type":'new'
    },
    {
        "id": 3,
        "Name": 'Sumsung TV',
        "price": '26',
        "image": 'image/p15.webp',
        "cat": 'tv',
        "type": 'new',
    },
    {
        "id": 3,
        "Name": 'Sumsung TV',
        "price": '26',
        "image": 'image/p13.jpeg',
        "cat": 'tv',
        "type": 'new',
    },
    {
        "id": 4,
        "Name": 'UV TV',
        "price": '26',
        "image": '',
        "cat": 'tv',
        "type": 'new',
    },
    {
        "id": 5,
        "Name": 'Dell',
        "price": '96',
        "image": '',
        "cat": 'laptop',
        "type": 'new',
    },
    {
        "id":6,
        "Name": 'Intex',
        "price": '96',
        "image": '',
        "cat": 'laptop',
        "type": 'new',
    },
    {
        "id": 7,
        "Name": 'Lenovo',
        "price": '96',
        "image": '',
        "cat": 'laptop',
        "type": 'new',
    },
    {
        "id": 8,
        "Name": 'HP',
        "price": '96',
        "image": '',
        "cat": 'laptop',
        "type": 'new',
    },
    {
        "id": 9,
        "Name": 'Headphone',
        "price": '96',
        "image": '',
        "cat": 'headphone',
        "type": 'new',
    },

    {
        "id": 10,
        "Name": 'Headphone',
        "price": '236',
        "image": 'image/p3.webp',
        "cat": 'headphone',
        "type": 'new',
    },
    {
        "id": 11,
        "Name": 'Headphone',
        "price": '636',
        "image": 'image/p9.jpg',
        "cat": 'headphone',
        "type": 'new',
    },
    {
        "id": 12,
        "Name": 'Headphone',
        "price": '98',
        "image": 'image/p4.webp',
        "cat": 'headphone',
        "type": 'featured',
    },
    {
        "id": 13,
        "Name": 'Smart Watch',
        "price": '59',
        "image": 'image/p5.webp',
        "cat": 'electronics',
        "type": 'featured',
    },
    {
        "id": 14,
        "Name": 'Smart Watch',
        "price": '956',
        "image": 'image/p10.jpg',
        "cat": 'electronics',
        "type": 'featured',
    },
    {
        "id": 15,
        "Name": 'Smart Watch',
        "price": '389',
        "image": 'image/p11.jpg',
        "cat": 'electronics',
        "type": 'featured',
    },
    {
        "id": 16,
        "Name": 'Smart Watch',
        "price": '67',
        "image": 'image/p6.webp',
        "cat": 'electronics',
        "type": 'top',
    },
    {
        "id": 17,
        "Name": 'Speaker',
        "price": '76',
        "image": 'image/p7.webp',
        "cat": 'electronics',
        "type": 'top',
    },
    {
        "id": 18,
        "Name": 'Speaker',
        "price": '87',
        "image": 'image/p8.webp',
        "cat": 'electronics',
        "type": 'top',
    },
    {
        "id": 19,
        "Name": 'product12',
        "price": '807',
        "image": 'image/p12.jpg',
        "cat": 'electronics',
        "type": 'top',
    }
]



module.exports={data};